var quotes = [
  ['If I stop to kick every barking dog, I am not going to get where I’m going.', 'Jackie Joyner-Kersee'],
  ['Optimism is the faith that leads to achievement', 'Helen Keller'],
  ['You are the one that possesses the keys to your being. You carry the passport to your own happiness.', 'Diane von Furstenberg'],
  ['I was smart enough to go through any door that opened.', 'Joan Rivers'],
  ['Cautious, careful people, always casting about to preserve their reputations can never effect a reform', 'Susan B. Anthony'],
  ['When the whole world is silent, even one voice becomes powerful.', 'Malala Yousafzai'],
  ['Make the most of yourself by fanning the tiny, inner sparks of possibility into flames of achievement.', 'Golda Meir'],
  ['Knowing what must be done does away with fear.', 'Rosa Parks'],
  ['I didn’t get there by wishing for it or hoping for it, but by working for it', 'Estée Lauder'],
  ['Power’s not given to you. You have to take it.', 'Beyoncé Knowles Carter'],
  ['The most difficult thing is the decision to act, the rest is merely tenacity.', ' Amelia Earhart'],
  ['The difference between successful people and others is how long they spend time feeling sorry for themselves.', 'Barbara Corcoran'],
  ['You can waste your life drawing lines. Or you can live your life crossing them.', 'Shonda Rhimes'],
  ['I’d rather regret the things I’ve done than regret the things I haven’t done.', ' Lucille Ball'],
  ['I hope the fathers and mothers of little girls will look at them and say ‘yes, women can.’', 'Dilma Rousseff'],
  ['If you don’t risk anything, you risk even more.', 'Erica Jong'],
  ['The way we talk to our children becomes their inner voice', 'Peggy O’Mara'],
  ['You can never leave footprints that last if you are always walking on tiptoe.', ' Leymah Gbowee'],
  ['If you don’t like the road you’re walking, start paving another one', 'Dolly Parton'],
  ['If you think taking care of yourself is selfish, change your mind. If you don’t, you’re simply ducking your responsibilities.', 'Ann Richards'],
  ['You can’t give up! If you give up, you’re like everybody else.', 'Chris Evert'],
  ['No matter how difficult and painful it may be, nothing sounds as good to the soul as the truth.', 'Martha Beck'],
  ['Done is better than perfect.', 'Sheryl Sandberg'],
  ['One of the secrets to staying young is to always do things you don’t know how to do, to keep learning.', 'Ruth Reichl'],
  ['Be first and be lonely.', 'Ginni Rometty'],
  ['One cannot accomplish anything without fanaticism.', 'Eva Perón'],
  ['Look your best - who said love is blind?', 'Mae West'],
  ['It took me quite a long time to develop a voice, and now that I have it, I am not going to be silent.', 'Madeleine Albright'],
  ['Step out of the history that is holding you back. Step into the new story you are willing to create.', 'Oprah Winfrey'],
  ['What you do makes a difference, and you have to decide what kind of difference you want to make.', 'Jane Goodall'],
  ['I firmly believe you never should spend your time being the former anything.', 'Condoleezza Rice'],
  ['A good compromise is one where everybody makes a contribution.', 'Angela Merkel'],
  ['A strong woman is a woman determined to do something others are determined not be done', 'Marge Piercy'],
  ['I choose to make the rest of my life the best of my life', 'Louise Hay'],
  ['Drama is very important in life: You have to come on with a bang. You never want to go out with a whimper.', 'Julia Child'],
  ['In order to be irreplaceable one must always be different.', 'Coco Chanel'],
  ['Spread love everywhere you go. Let no one ever come to you without leaving happier', 'Mother Teresa'],
  ['Take criticism seriously, but not personally. If there is truth or merit in the criticism, try to learn from it. Otherwise, let it roll right off you.', 'Hillary Clinton'],
  ['Learn from the mistakes of others. You can’t live long enough to make them all yourself.', 'Eleanor Roosevelt'],
  ['Women will only have true equality when men share with them the responsibility of bringing up the next generation', 'Ruth Bader Ginsburg'],
  ['Above all, be the heroine of your life, not the victim.', 'Nora Ephron'],
  ['Change your life today. Don’t gamble on the future, act now, without delay.', 'Simone de Beauvoir'],
  ['If you’re not making some notable mistakes along the way, you’re certainly not taking enough business and career chances', 'Sallie Krawcheck'],
  ['A surplus of effort could overcome a deficit of confidence', 'Sonia Sotomayor'],
  ['You can be the lead in your own life', 'Kerry Washington'],
  ['No one changes the world who isn’t obsessed', 'Billie Jean King'],
  ['Normal is not something to aspire to, it’s something to get away from.', 'Jodie Foster'],
  ['I am always busy, which is perhaps the chief reason why I am always well', 'Elizabeth Cady Stanton'],
  ['When I’m hungry, I eat. When I’m thirsty, I drink. When I feel like saying something, I say it.', 'Madonna'],
  ['I do not try to dance better than anyone else. I only try to dance better than myself.', 'Arianna Huffington'],
  ['I’m always perpetually out of my comfort zone', 'Tory Burch'],
  ['If you can’t go straight ahead, you go around the corner', 'Cher'],
  ['If you don’t get out of the box you’ve been raised in, you won’t understand how much bigger the world is', 'Angelina Jolie'],
  ['Everyone shines, given the right lighting.', 'Susan Cain'],
  ['If you’re someone people count on, particularly in difficult moments, that’s a sign of a life lived honorably', 'Rachel Maddow'],
  ['If you just set out to be liked, you would be prepared to compromise on anything at any time, and you would achieve nothing', 'Margaret Thatcher'],
  ['Don’t look at your feet to see if you are doing it right. Just dance', 'Anne Lamott'],
  ['All careers go up and down like friendships, like marriages, like anything else, and you can’t bat a thousand all the time.', 'Julie Andrews'],
  ['If you find someone you love in your life, then hang on to that love.', ' Princess Diana'],
  ['We do not need magic to change the world, we carry all the power we need inside ourselves already: we have the power to imagine better', 'J.K. Rowling'],
  ['When you’re through changing, you’re through', 'Martha Stewart'],
  ['Cherish forever what makes you unique, cuz you’re really a yawn if it goes', ' Bette Midler'],
  ['Style is a way to say who you are without having to speak.', 'Rachel Zoe'],
  ['Dying seems less sad than having lived too little.', 'Gloria Steinem'],
  ['Many receive advice, only the wise profit from it.', 'Harper Lee'],
];