var quotes = [
  ['If I stop to kick every barking dog, I am not going to get where I’m going.', 'Jackie Joyner-Kersee'],
  ['Optimism is the faith that leads to achievement', 'Helen Keller'],
  ['You are the one that possesses the keys to your being. You carry the passport to your own happiness.', 'Diane von Furstenberg'],
  ['I was smart enough to go through any door that opened.', 'Joan Rivers'],
  ['Cautious, careful people, always casting about to preserve their reputations can never effect a reform', 'Susan B. Anthony'],
  ['When the whole world is silent, even one voice becomes powerful.', 'Malala Yousafzai'],
  ['Make the most of yourself by fanning the tiny, inner sparks of possibility into flames of achievement.', 'Golda Meir'],
  ['Knowing what must be done does away with fear.', 'Rosa Parks'],
  ['I didn’t get there by wishing for it or hoping for it, but by working for it', 'Estée Lauder'],
  ['Power’s not given to you. You have to take it.', 'Beyoncé Knowles Carter'],
  ['The most difficult thing is the decision to act, the rest is merely tenacity.', ' Amelia Earhart'],
  ['The difference between successful people and others is how long they spend time feeling sorry for themselves.','Barbara Corcoran'],
  ['You can waste your lives drawing lines. Or you can live your life crossing them.','Shonda Rhimes'],
  ['I’d rather regret the things I’ve done than regret the things I haven’t done.',' Lucille Ball'],
  ['I hope the fathers and mothers of little girls will look at them and say ‘yes, women can.’','Dilma Rousseff'],
  ['Beware of monotony; it’s the mother of all the deadly sins.','Edith Wharton'],
  ['If you don’t risk anything, you risk even more.','Erica Jong'],
  ['I have stood on a mountain of no’s for one yes.','B. Smith'],
  ['The way we talk to our children becomes their inner voice','Peggy O’Mara'],
  ['You can never leave footprints that last if you are always walking on tiptoe.',' Leymah Gbowee'],
  ['If you don’t like the road you’re walking, start paving another one','Dolly Parton'],
  ['If you think taking care of yourself is selfish, change your mind. If you don’t, you’re simply ducking your responsibilities.','Ann Richards'],

];